spring.application.name=filesharingapp
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultlinkdb
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mysupersecretkeymysupersecretkey
jwt.access.expiration=900000
jwt.expiration=900000
jwt.refresh.expiration=604800000

file.upload-dir=uploads

file.max-size=100MB
file.default-storage-limit=1GB

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=1GB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support.vaultlink@gmail.com
spring.mail.password=jzkw nund xwla gbzi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# rate limit config
app.password-reset.max-requests=3
app.password-reset.expiry-minutes=15

# Backend API
app.base-url=http://localhost:8080

# Frontend (for share links opened in browser)
app.frontend-url=http://localhost:5173